In [3]:
# Import librerie
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Setup completo")
print(f"Pandas: {pd.__version__}")
print(f"Seaborn: {sns.__version__}")

Setup completo
Pandas: 3.0.1
Seaborn: 0.13.2

In [4]:
from pathlib import Path

# Path ai dati
DATA_DIR = Path("../data")

# Carica le tre stagioni
df_2223 = pd.read_csv(DATA_DIR / "serie_a_2022_23.csv")
df_2324 = pd.read_csv(DATA_DIR / "serie_a_2023_24.csv")
df_2425 = pd.read_csv(DATA_DIR / "serie_a_2024_25.csv")

# Unisci tutto in un unico DataFrame
df = pd.concat([df_2223, df_2324, df_2425], ignore_index=True)

print(f"Righe totali: {len(df)}")
print(f"Colonne: {df.columns.tolist()}")

Righe totali: 1140
Colonne: ['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA']

In [6]:
df_dropped=df.drop(['Div', 'Date', 'Time', 'HTHG', 'HTAG', 'HTR', 'HS', 'AS', 'HST', 'AST', 'HF', 'AF', 'HC', 'AC', 'HY', 'AY', 'HR', 'AR', 'B365H', 'B365D', 'B365A', 'BWH', 'BWD', 'BWA', 'IWH', 'IWD', 'IWA', 'PSH', 'PSD', 'PSA', 'WHH', 'WHD', 'WHA', 'VCH', 'VCD', 'VCA', 'MaxH', 'MaxD', 'MaxA', 'AvgH', 'AvgD', 'AvgA', 'B365>2.5', 'B365<2.5', 'P>2.5', 'P<2.5', 'Max>2.5', 'Max<2.5', 'Avg>2.5', 'Avg<2.5', 'AHh', 'B365AHH', 'B365AHA', 'PAHH', 'PAHA', 'MaxAHH', 'MaxAHA', 'AvgAHH', 'AvgAHA', 'B365CH', 'B365CD', 'B365CA', 'BWCH', 'BWCD', 'BWCA', 'IWCH', 'IWCD', 'IWCA', 'PSCH', 'PSCD', 'PSCA', 'WHCH', 'WHCD', 'WHCA', 'VCCH', 'VCCD', 'VCCA', 'MaxCH', 'MaxCD', 'MaxCA', 'AvgCH', 'AvgCD', 'AvgCA', 'B365C>2.5', 'B365C<2.5', 'PC>2.5', 'PC<2.5', 'MaxC>2.5', 'MaxC<2.5', 'AvgC>2.5', 'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH', 'MaxCAHA', 'AvgCAHH', 'AvgCAHA', 'BFH', 'BFD', 'BFA', '1XBH', '1XBD', '1XBA', 'BFEH', 'BFED', 'BFEA', 'BFE>2.5', 'BFE<2.5', 'BFEAHH', 'BFEAHA', 'BFCH', 'BFCD', 'BFCA', '1XBCH', '1XBCD', '1XBCA', 'BFECH', 'BFECD', 'BFECA', 'BFEC>2.5', 'BFEC<2.5', 'BFECAHH', 'BFECAHA'], axis=1)

In [8]:
print(f"colonne: {df_dropped.columns.tolist()}")

colonne: ['HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR']

In [9]:
df_dropped.head()

     HomeTeam   AwayTeam  FTHG  FTAG FTR
0       Milan    Udinese     4     2   H
1   Sampdoria   Atalanta     0     2   A
2       Lecce      Inter     1     2   A
3       Monza     Torino     1     2   A
4  Fiorentina  Cremonese     3     2   H

In [13]:
print(df_dropped.isna().count())

HomeTeam    1140
AwayTeam    1140
FTHG        1140
FTAG        1140
FTR         1140
dtype: int64

In [ ]:
ftr=df_dropped['FTR'].map(lambda x: if x = "D"

In [75]:
h=df_dropped.groupby(["HomeTeam"]).sum()
a=df_dropped.groupby(["AwayTeam"]).sum()
gol_fatti_in_casa=pd.DataFrame(data=h, columns=['FTHG'])
gol_subiti_in_casa=pd.DataFrame(data=h, columns=['FTAG'])
gol_fatti_in_trasferta=pd.DataFrame(data=a, columns=['FTAG'])
gol_subiti_in_trasferta=pd.DataFrame(data=a, columns=['FTHG'])

In [78]:
gol_fatti_in_casa.columns = ['gol']
gol_fatti_in_trasferta.columns = ['gol']

In [90]:
gol_subiti_in_casa.columns = ['gol']
gol_subiti_in_trasferta.columns = ['gol']
gol_subiti = gol_subiti_in_casa + gol_subiti_in_trasferta

In [91]:
gol_fatti=gol_fatti_in_casa+gol_fatti_in_trasferta

In [92]:
gol_subiti

             gol
HomeTeam
Atalanta     127
Bologna      128
Cagliari     124
Como          52
Cremonese     69
Empoli       162
Fiorentina   130
Frosinone     69
Genoa         94
Inter         99
Juventus      99
Lazio        118
Lecce        158
Milan        135
Monza        172
Napoli       103
Parma         58
Roma         119
Salernitana  143
Sampdoria     71
Sassuolo     136
Spezia        62
Torino       122
Udinese      157
Venezia       56
Verona       176

In [93]:
df_finale = pd.concat([gol_fatti, gol_subiti], axis=1)

In [94]:
df_finale.columns=['GOL FATTI', 'GOL SUBITI']

In [95]:
df_finale

             GOL FATTI  GOL SUBITI
HomeTeam
Atalanta           216         127
Bologna            164         128
Cagliari            82         124
Como                49          52
Cremonese           36          69
Empoli              99         162
Fiorentina         174         130
Frosinone           44          69
Genoa               82          94
Inter              239          99
Juventus           168          99
Lazio              170         118
Lecce               92         158
Milan              201         135
Monza              115         172
Napoli             191         103
Parma               44          58
Roma               171         119
Salernitana         80         143
Sampdoria           24          71
Sassuolo            90         136
Spezia              31          62
Torino             117         122
Udinese            125         157
Venezia             32          56
Verona             103         176